export const SET_PRODUCT_TOPPING = "overlay/SET_PRODUCT_TOPPING";

export const SET_PRODUCT_CONFIGURATION = "overlay/SET_PRODUCT_CONFIGURATION";

export const REMOVE_ALL_PRODUCT_TOPPINGS = "overlay/REMOVE_ALLPRODUCT_TOPPINGS";

export const RESET_PRODUCT_CONFIGURATION =
  "overlay/RESET_PRODUCT_CONFIGURATION";

export const CLEAR_OVERLAY = "overlay/CLEAR_OVERLAY";
